(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ack-and-a-half")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "dash-at-point")
(depends-on "evil")
(depends-on "evil-numbers")
(depends-on "flycheck")
(depends-on "grizzl")
(depends-on "highlight-indentation")
(depends-on "linum-relative")
(depends-on "markdown-mode")
(depends-on "noctilux-theme")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "slim-mode")
(depends-on "solarized-theme")
(depends-on "sublime-themes")
(depends-on "surround")
(depends-on "web-mode")
(depends-on "whitespace-cleanup-mode")
(depends-on "yard-mode")