(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "dash-at-point")
(depends-on "enh-ruby-mode")
(depends-on "evil")
(depends-on "evil-numbers")
(depends-on "grizzl")
(depends-on "highlight-indentation")
(depends-on "linum-relative")
(depends-on "noctilux-theme")
(depends-on "pallet")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "sublime-themes")
(depends-on "surround")
(depends-on "web-mode")
(depends-on "yard-mode")